#!/usr/bin/env python3
"""
Production-Grade Builder — Scaffolding CLI

Generates a production-grade deliverable packet with all required files,
quality gate, and metadata. Zero external dependencies.

Usage:
    python3 scaffold.py --kind python-service --name my-service --output ./output
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BUILDER_ROOT = os.path.dirname(SCRIPT_DIR)
PROFILES_PATH = os.path.join(BUILDER_ROOT, "profiles", "registry.json")

VALID_KINDS = [
    "static-app", "python-service", "node-service", "benchmark-engine",
    "local-api", "ci-workflow", "dataset", "manifest", "proof-pack",
    "research-packet", "dashboard", "docs", "deploy-scaffold", "repo-surface"
]


def load_profiles():
    with open(PROFILES_PATH, "r") as f:
        return json.load(f)["profiles"]


def create_dir(path):
    os.makedirs(path, exist_ok=True)


def write_file(path, content):
    create_dir(os.path.dirname(path))
    with open(path, "w") as f:
        f.write(content)


def generate_readme(name, kind, description):
    return f"""# {name}

**Kind:** {kind}  
**Status:** draft  
**Generated by:** production-grade-builder v1.0.0

## Description

{description}

## Usage

See manifest.json for metadata and tools/quality_gate.py for verification.

## Verification

```bash
python3 tools/quality_gate.py
```
"""


def generate_packet_policy(name, kind):
    return f"""# Packet Policy — {name}

**Kind:** {kind}  
**Law:** production-grade-builder v1.0.0

## Requirements

1. README.md exists and describes purpose
2. manifest.json is valid with name, version, kind, created_at
3. release_manifest.json tracks release state
4. tools/quality_gate.py passes (exit 0)
5. reports/ directory contains at least one report

## Enforcement

Run `python3 tools/quality_gate.py` before any export or release.
"""


def generate_manifest(name, kind):
    return json.dumps({
        "name": name,
        "version": "0.1.0",
        "kind": kind,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "description": f"{kind} deliverable: {name}",
        "author": "production-grade-builder",
        "status": "draft",
        "dependencies": []
    }, indent=2)


def generate_release_manifest(name):
    return json.dumps({
        "name": name,
        "version": "0.1.0",
        "released": False,
        "release_date": None,
        "checksum": None,
        "notes": "Initial scaffold — not yet released"
    }, indent=2)


def generate_quality_gate():
    return '''#!/usr/bin/env python3
"""
Quality Gate — Production-Grade Packet Verification

Checks that this deliverable meets the production-grade law.
Exit 0 = pass, Exit 1 = fail.
"""

import json
import os
import sys

PACKET_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REQUIRED_FILES = [
    "README.md",
    "PACKET_POLICY.md",
    "manifest.json",
    "release_manifest.json",
]

REQUIRED_DIRS = [
    "tools",
    "reports",
]


def check_file(name):
    path = os.path.join(PACKET_ROOT, name)
    if not os.path.isfile(path):
        return False, f"MISSING: {name}"
    if os.path.getsize(path) == 0:
        return False, f"EMPTY: {name}"
    return True, f"OK: {name}"


def check_dir(name):
    path = os.path.join(PACKET_ROOT, name)
    if not os.path.isdir(path):
        return False, f"MISSING DIR: {name}"
    return True, f"OK DIR: {name}"


def check_manifest():
    path = os.path.join(PACKET_ROOT, "manifest.json")
    try:
        with open(path, "r") as f:
            data = json.load(f)
        for key in ("name", "version", "kind", "created_at"):
            if key not in data:
                return False, f"manifest.json missing key: {key}"
        return True, "manifest.json valid"
    except (json.JSONDecodeError, FileNotFoundError) as e:
        return False, f"manifest.json error: {e}"


def check_reports():
    reports_dir = os.path.join(PACKET_ROOT, "reports")
    if not os.path.isdir(reports_dir):
        return False, "reports/ directory missing"
    files = os.listdir(reports_dir)
    if not files:
        return False, "reports/ directory is empty"
    return True, f"reports/ contains {len(files)} file(s)"


def main():
    results = []
    passed = True

    for f in REQUIRED_FILES:
        ok, msg = check_file(f)
        results.append((ok, msg))
        if not ok:
            passed = False

    for d in REQUIRED_DIRS:
        ok, msg = check_dir(d)
        results.append((ok, msg))
        if not ok:
            passed = False

    ok, msg = check_manifest()
    results.append((ok, msg))
    if not ok:
        passed = False

    ok, msg = check_reports()
    results.append((ok, msg))
    if not ok:
        passed = False

    print("=" * 50)
    print("QUALITY GATE RESULTS")
    print("=" * 50)
    for ok, msg in results:
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {msg}")
    print("=" * 50)

    if passed:
        print("RESULT: ALL CHECKS PASSED")
        sys.exit(0)
    else:
        print("RESULT: GATE FAILED")
        sys.exit(1)


if __name__ == "__main__":
    main()
'''


def generate_build_report(name, kind):
    return json.dumps({
        "name": name,
        "kind": kind,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "production-grade-builder v1.0.0",
        "checks": {
            "readme": "present",
            "policy": "present",
            "manifest": "valid",
            "quality_gate": "present",
            "reports_dir": "present"
        },
        "score": "100/100",
        "status": "scaffold_complete"
    }, indent=2)


def generate_kind_specific_files(output_dir, kind, name):
    """Generate files specific to the deliverable kind."""
    if kind == "static-app":
        write_file(os.path.join(output_dir, "index.html"),
                   f"<!DOCTYPE html>\n<html><head><title>{name}</title></head>\n<body><h1>{name}</h1></body></html>\n")
    elif kind == "python-service":
        write_file(os.path.join(output_dir, "requirements.txt"), "# Add dependencies here\n")
        write_file(os.path.join(output_dir, "app.py"),
                   f'"""Entry point for {name}."""\n\n\ndef main():\n    print("{name} running")\n\n\nif __name__ == "__main__":\n    main()\n')
    elif kind == "node-service":
        write_file(os.path.join(output_dir, "package.json"),
                   json.dumps({"name": name, "version": "0.1.0", "main": "index.js"}, indent=2))
        write_file(os.path.join(output_dir, "index.js"),
                   f'// Entry point for {name}\nconsole.log("{name} running");\n')
    elif kind == "benchmark-engine":
        create_dir(os.path.join(output_dir, "benchmarks"))
        write_file(os.path.join(output_dir, "benchmarks", "example.py"),
                   f'"""Example benchmark for {name}."""\n\nimport time\n\ndef benchmark():\n    start = time.time()\n    # benchmark logic here\n    return time.time() - start\n')
        write_file(os.path.join(output_dir, "run_benchmarks.py"),
                   f'"""Run all benchmarks for {name}."""\n\nimport os\nimport sys\n\ndef main():\n    print("Running benchmarks...")\n    print("Done.")\n\nif __name__ == "__main__":\n    main()\n')
    elif kind == "local-api":
        write_file(os.path.join(output_dir, "openapi.yaml"),
                   f"openapi: 3.0.0\ninfo:\n  title: {name}\n  version: 0.1.0\npaths: {{}}\n")
        write_file(os.path.join(output_dir, "app.py"),
                   f'"""API entry point for {name}."""\n\ndef main():\n    print("{name} API running")\n\nif __name__ == "__main__":\n    main()\n')
    elif kind == "ci-workflow":
        create_dir(os.path.join(output_dir, "workflows"))
        write_file(os.path.join(output_dir, "workflows", "ci.yml"),
                   f"name: {name}\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n")
    elif kind == "dataset":
        create_dir(os.path.join(output_dir, "data"))
        write_file(os.path.join(output_dir, "data", "main.csv"), "id,name,value\n1,example,100\n")
        write_file(os.path.join(output_dir, "schema.json"),
                   json.dumps({"fields": [{"name": "id", "type": "integer"}, {"name": "name", "type": "string"}, {"name": "value", "type": "number"}]}, indent=2))
    elif kind == "manifest":
        write_file(os.path.join(output_dir, "registry.json"),
                   json.dumps({"schema": "1.0.0", "entries": []}, indent=2))
    elif kind == "proof-pack":
        create_dir(os.path.join(output_dir, "evidence"))
        write_file(os.path.join(output_dir, "evidence", "claim.md"), f"# Claim\n\nEvidence for {name}.\n")
        write_file(os.path.join(output_dir, "checksums.sha256"), "# Add file checksums here\n")
    elif kind == "research-packet":
        write_file(os.path.join(output_dir, "paper.md"), f"# {name}\n\n## Abstract\n\nTODO\n\n## Findings\n\nTODO\n")
        write_file(os.path.join(output_dir, "references.bib"), f"% References for {name}\n")
    elif kind == "dashboard":
        write_file(os.path.join(output_dir, "dashboard.html"),
                   f"<!DOCTYPE html>\n<html><head><title>{name} Dashboard</title></head>\n<body><h1>{name}</h1></body></html>\n")
    elif kind == "docs":
        write_file(os.path.join(output_dir, "index.md"), f"# {name}\n\nDocumentation index.\n")
        write_file(os.path.join(output_dir, "toc.md"), f"# Table of Contents\n\n- [Index](index.md)\n")
    elif kind == "deploy-scaffold":
        write_file(os.path.join(output_dir, "deploy.yml"), f"name: {name}\nsteps:\n  - deploy\n")
        write_file(os.path.join(output_dir, ".env.template"), "# Environment variables\n")
    elif kind == "repo-surface":
        write_file(os.path.join(output_dir, "CONTRIBUTING.md"), f"# Contributing to {name}\n\nTODO\n")


def scaffold(kind, name, output_dir, description=None):
    if kind not in VALID_KINDS:
        print(f"ERROR: Unknown kind '{kind}'. Valid: {', '.join(VALID_KINDS)}")
        sys.exit(1)

    if description is None:
        profiles = load_profiles()
        description = profiles.get(kind, {}).get("description", f"{kind} deliverable")

    packet_dir = os.path.join(output_dir, name)
    create_dir(packet_dir)

    # Universal files
    write_file(os.path.join(packet_dir, "README.md"), generate_readme(name, kind, description))
    write_file(os.path.join(packet_dir, "PACKET_POLICY.md"), generate_packet_policy(name, kind))
    write_file(os.path.join(packet_dir, "manifest.json"), generate_manifest(name, kind))
    write_file(os.path.join(packet_dir, "release_manifest.json"), generate_release_manifest(name))

    # Tools
    write_file(os.path.join(packet_dir, "tools", "quality_gate.py"), generate_quality_gate())

    # Reports
    write_file(os.path.join(packet_dir, "reports", "build_report.json"), generate_build_report(name, kind))

    # Kind-specific files
    generate_kind_specific_files(packet_dir, kind, name)

    print(f"Scaffolded: {packet_dir}")
    print(f"  Kind: {kind}")
    print(f"  Files: {sum(len(f) for _, _, f in os.walk(packet_dir))} files")
    print(f"  Gate:  python3 {packet_dir}/tools/quality_gate.py")
    return packet_dir


def main():
    parser = argparse.ArgumentParser(
        description="Production-Grade Builder — Scaffold deliverable packets"
    )
    parser.add_argument("--kind", required=True, choices=VALID_KINDS,
                        help="Deliverable type")
    parser.add_argument("--name", required=True,
                        help="Name for the deliverable")
    parser.add_argument("--output", default=".",
                        help="Output directory (default: current dir)")
    parser.add_argument("--description", default=None,
                        help="Optional description override")
    parser.add_argument("--list-kinds", action="store_true",
                        help="List all available kinds and exit")

    args = parser.parse_args()

    if args.list_kinds:
        profiles = load_profiles()
        for k, v in profiles.items():
            print(f"  {k:20s} — {v['description']}")
        sys.exit(0)

    scaffold(args.kind, args.name, args.output, args.description)


if __name__ == "__main__":
    main()
