#!/bin/bash
# generate-docs.sh - Generate documentation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

echo "════════════════════════════════════════════════════════════════"
echo "            DOCUMENTATION GENERATION                            "
echo "════════════════════════════════════════════════════════════════"
echo ""

DOCS_DIR="docs/generated"
mkdir -p "$DOCS_DIR"

echo "Generating API documentation..."
if [ -d "src/python" ]; then
    export PYTHONPATH="$SCRIPT_DIR/src/python:$PYTHONPATH"
    
    # Generate docstrings
    find src/python -name "*.py" -type f -exec grep -l "def " {} \; | head -10 > "$DOCS_DIR/modules.txt"
    echo "  ✓ Module list generated"
fi

# Generate README section
cat > "$DOCS_DIR/SCRIPTS_GENERATED.md" << 'EOF'
# Generated Build Scripts

This file was automatically generated by generate-docs.sh

## Testing Scripts

- `test-python.sh` - Run Python test suite
- `test-julia.sh` - Run Julia/THESIS tests
- `test-rust.sh` - Run Rust tests
- `test-javascript.sh` - Run JavaScript tests
- `test-haskell.sh` - Run Haskell tests
- `test-all.sh` - Run all test suites
- `test-coverage.sh` - Generate coverage reports
- `test-protocols.sh` - Validate protocols
- `test-governance.sh` - Test governance layer
- `test-integration.sh` - Run integration tests

## Build Scripts

- `build-python.sh` - Build Python package
- `build-julia.sh` - Build Julia package
- `build-rust.sh` - Build Rust crates
- `build-javascript.sh` - Build JavaScript packages
- `build-docker.sh` - Build Docker images
- `build-all.sh` - Build all components
- `build-release.sh` - Create release artifacts
- `build-artifacts.sh` - Collect artifacts

## Deployment Scripts

- `deploy-local.sh` - Deploy locally with Docker Compose
- `deploy-docker.sh` - Push Docker images
- `deploy-kubernetes.sh` - Deploy to Kubernetes
- `deploy-staging.sh` - Deploy to staging
- `deploy-production.sh` - Deploy to production
- `deploy-rollback.sh` - Rollback deployment
- `deploy-verify.sh` - Verify deployment health

## Utility Scripts

- `setup-dev-env.sh` - Set up development environment
- `setup-ci.sh` - Set up CI/CD environment
- `verify-deps.sh` - Verify dependencies
- `lint-all.sh` - Run all linters
- `format-code.sh` - Format all code
- `generate-docs.sh` - Generate documentation
- `health-check.sh` - Check system health
- `cleanup.sh` - Clean up temporary files
- `backup.sh` - Backup important data
- `restore.sh` - Restore from backup
- `check-security.sh` - Run security checks
- `update-deps.sh` - Update dependencies
EOF

echo "  ✓ Documentation generated"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✓ Documentation complete: $DOCS_DIR"
echo "════════════════════════════════════════════════════════════════"
